<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_convert</name>
   <tag></tag>
   <elementGuidId>ea2b461e-2fc5-4be0-b504-480c343f3610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'processTask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processTask</value>
      <webElementGuid>53c4feaf-a881-4798-824b-06cf13060473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31c88c37-6a6c-4e9c-b564-6b7c7b1ba5f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
